#!/bin/bash

#
# Lemon downloader
#
# This script downloads you lemon using git and deletes files you don't need
#
#

# Colors
YELLOW='\033[0;33m'
RED='\033[0;31m'
END='\033[0m'

# Start
echo ""
echo -e "${YELLOW}Lemon Downloader${END}"
echo "================"
echo ""

name="lemon_example"

if [ -d "$name" ];
then
    echo -e "${RED}Folder '$name' already exist! ${END}"
    exit 1
fi

# Downloading
echo -e "${YELLOW}Building project in '$name' folder...${END}"
echo ""
git clone https://github.com/Lemon-Framework/Lemon.git $name

# Removing
rm $name/README.md
rm $name/LICENCE.md
rm $name/composer.json

# End
echo ""
echo -e "${YELLOW}Done! Now do some stuff!${END}"

